# Generated by Django 4.0.4 on 2022-05-30 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Project Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('tech_stack', models.CharField(choices=[(0, 'Vue'), (1, 'React'), (2, 'Angular')], max_length=1, null=True, verbose_name='Tech Stack')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
